spring:
    datasource:
        url: jdbc:mysql://localhost:3306/your_db_name
        username: your_db_username
        password: your_db_password
        driver-class-name: com.mysql.cj.jdbc.Driver
